In [1]:
import pandas as pd
import os
import glob

### get all the tables, add a column for year and join them together

In [2]:
files = glob.glob('./data/*_data.csv')
files

['./data\\2010_data.csv',
 './data\\2011_data.csv',
 './data\\2012_data.csv',
 './data\\2013_data.csv',
 './data\\2014_data.csv',
 './data\\2015_data.csv',
 './data\\2016_data.csv',
 './data\\2017_data.csv']

In [3]:
dfs = []
for file in files:
    df = pd.read_csv(file)
    year = file.split('\\')[1].split('_')[0]
    df['year'] = year
    dfs.append(df)

In [4]:
dfs[0].head()

,Player,Team,Opponent,Location,Pts*,Att,Cmp,Yds,TD,Int,...,TD.1,2Pt.1,Rec,Yds.2,TD.2,2Pt.2,FL,TD.3,Week,year
0,Arian Foster,HOU,@IND,away,42.0,0,0,0,0,0,...,3,0,1,7,0,0,0,0,1,2010
1,Matt Forte,CHI,@DET,away,38.0,0,0,0,0,0,...,0,0,7,151,2,0,1,0,1,2010
2,Peyton Manning,IND,HOU,home,35.0,57,40,433,3,0,...,0,0,0,0,0,0,0,0,1,2010
3,Chad Johnson,CIN,NE,home,33.0,0,0,0,0,0,...,0,0,12,159,1,0,0,0,1,2010
4,Austin Collie,IND,HOU,home,32.0,0,0,0,0,0,...,0,0,11,163,1,0,1,0,1,2010

In [5]:
df = pd.concat(dfs, axis=0)
df.shape

(12800, 23)

In [6]:
df.head()

,Player,Team,Opponent,Location,Pts*,Att,Cmp,Yds,TD,Int,...,TD.1,2Pt.1,Rec,Yds.2,TD.2,2Pt.2,FL,TD.3,Week,year
0,Arian Foster,HOU,@IND,away,42.0,0,0,0,0,0,...,3,0,1,7,0,0,0,0,1,2010
1,Matt Forte,CHI,@DET,away,38.0,0,0,0,0,0,...,0,0,7,151,2,0,1,0,1,2010
2,Peyton Manning,IND,HOU,home,35.0,57,40,433,3,0,...,0,0,0,0,0,0,0,0,1,2010
3,Chad Johnson,CIN,NE,home,33.0,0,0,0,0,0,...,0,0,12,159,1,0,0,0,1,2010
4,Austin Collie,IND,HOU,home,32.0,0,0,0,0,0,...,0,0,11,163,1,0,1,0,1,2010

### Load player position data and merge with first df

In [7]:
player_pos = pd.read_csv("./data/player_pos.csv")
player_pos.head()

          Player Position
0     A.J. Derby       TE
1    A.J. Feeley       QB
2     A.J. Green       WR
3   A.J. Jenkins       WR
4  A.J. McCarron       QB

In [8]:
new_df = pd.merge(df, player_pos, on='Player', how='left')
new_df.head(20)

,Player,Team,Opponent,Location,Pts*,Att,Cmp,Yds,TD,Int,...,2Pt.1,Rec,Yds.2,TD.2,2Pt.2,FL,TD.3,Week,year,Position
0,Arian Foster,HOU,@IND,away,42.0,0,0,0,0,0,...,0,1,7,0,0,0,0,1,2010,RB
1,Matt Forte,CHI,@DET,away,38.0,0,0,0,0,0,...,0,7,151,2,0,1,0,1,2010,RB
2,Peyton Manning,IND,HOU,home,35.0,57,40,433,3,0,...,0,0,0,0,0,0,0,1,2010,QB
3,Chad Johnson,CIN,NE,home,33.0,0,0,0,0,0,...,0,12,159,1,0,0,0,1,2010,WR
4,Austin Collie,IND,HOU,home,32.0,0,0,0,0,0,...,0,11,163,1,0,1,0,1,2010,WR
5,Chris Johnson,TEN,@OAK,away,30.0,0,0,0,0,0,...,0,4,8,0,0,0,0,1,2010,RB
6,Miles Austin,DAL,WAS,home,30.0,0,0,0,0,0,...,0,10,146,1,0,0,0,1,2010,WR
7,Hakeem Nicks,NYG,@CAR,away,29.0,0,0,0,0,0,...,0,4,75,3,0,0,0,1,2010,WR
8,Tom Brady,NE,@CIN,away,28.0,35,25,258,3,0,...,0,0,0,0,0,0,0,1,2010,QB
9,Wes Welker,NE,@CIN,away,26.0,0,0,0,0,0,...,0,8,64,2,0,0,0,1,2010,WR
10,Darren McFadden,OAK,TEN,home,26.0,0,0,0,0,0,...,0,6,55,1,0,0,0,1,2010,RB
11,David Garrard,JAX,@DEN,away,25.0,21,16,170,3,0,...,0,0,0,0,0,0,0,1,2010,QB
12,Jay Cutler,CHI,@DET,away,25.0,35,23,372,2,1,...,0,0,0,0,0,1,0,1,2010,QB
13,Dallas Clark,IND,HOU,home,25.0,0,0,0,0,0,...,0,11,80,1,0,0,0,1,2010,TE
14,Roddy White,ATL,PIT,home,24.0,0,0,0,0,0,...,0,13,111,0,0,0,0,1,2010,WR
15,Michael Vick,PHI,@GB,away,23.0,24,16,175,1,0,...,0,0,0,0,0,0,0,1,2010,QB
16,Philip Rivers,SD,KC,home,23.0,39,22,298,2,0,...,0,0,0,0,0,0,0,1,2010,QB
17,Carson Palmer,CIN,NE,home,23.0,50,34,345,2,1,...,0,0,0,0,0,0,0,1,2010,QB
18,Reggie Wayne,IND,HOU,home,22.0,0,0,0,0,0,...,0,7,99,1,0,0,0,1,2010,WR
19,Legedu Naanee,SD,KC,home,22.0,0,0,0,0,0,...,0,5,110,1,0,0,0,1,2010,WR

### Check if any missing, if so, get the missing players and fill in manually, then add them to the original player_pos list and delete all entries where the position is null

In [9]:
new_df.loc[:, 'Position'].isnull().sum()

0

In [10]:
null_vec = new_df.loc[:, 'Position'].isnull()
new_df[null_vec.values].loc[:, 'Player'].unique()

array([], dtype=object)

In [11]:
missing = pd.Series(new_df[null_vec.values].loc[:, 'Player'].unique())

In [12]:
missing.to_csv("./data/missing.csv", index=None)

In [13]:
# update header and write to disk
new_df.columns = ['Player', 'Team', 'Opponent', 'Location', 'Pts', 'Att', 'Cmp', 'Yds',
       'TD', 'Int', '2Pt', 'Rush Att', 'Rush Yds', 'Rush TD', 'Rush 2Pt', 'Rec', 'Rec Yds',
       'Rec TD', 'Rec 2Pt', 'FL', 'Misc TD', 'Week', 'Year', 'Position']

In [14]:
new_df.to_csv("./data/full_data_set.csv", index=None)